"""Updated column names

Revision ID: dbc83f6db22e
Revises: 
Create Date: 2025-03-14 21:46:01.826661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc83f6db22e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_url', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('short_url', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint("uq_short_url", ['short_url'])
        batch_op.drop_column('short')
        batch_op.drop_column('long')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('short', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('short_url')
        batch_op.drop_column('original_url')

    # ### end Alembic commands ###
